# サイト設定
title: "こよみがかり ユーザーガイド"
description: "Discordコミュニティの予定をGoogleカレンダーと連携して管理するBOTシステム"
baseurl: "/koyomi-gakari-user-guide" # リポジトリ名と同じ
url: "https://mae-benten.github.io" # あなたのGitHubユーザー名に変更

# Jekyll設定
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# プラグイン
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# テーマ（オプション）
# theme: minima
# remote_theme: pages-themes/minimal@v0.2.0

# 除外ファイル
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# デフォルト設定
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# ナビゲーション
navigation:
  - name: "ホーム"
    link: "/"
  - name: "GitHub"
    link: "https://github.com/mae-benten/koyomi-gakari-user-guide"